spring:
  kafka:
    producer:
      bootstrap-servers: 13.124.198.63:9092
      acks: all
    consumer:
      bootstrap-servers: 13.124.198.63:9092
    listener:
      ack-mode: manual_immediate
      type: single
